# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c58dd4f5e0f588f6084f75bea82d75f6f2bcd4b7c8e622a5da601e9b81b7ae1aef2d3e0f329a701290371b4d46251273b5495fe73d76950b900598fb8b191702

test:
  secret_key_base: 10cdc66f46657daaafced07ccc4b1620f9a279678534d5508ac36e1a20dbc8f904b0c75a32702165250cc07782beed100d7990d5031aafbd8753656a26a90d68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
